[tool.poetry]
name = "evoflow-reactor"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
rshell = "^0.0.32"
db = { path = "../evoflow-monitor/evohub/db", develop =true}
# db = { git = "git@github.com:Schwank-Lab/evoflow-monitor.git", branch = "deploy", subdirectory = "evohub/db" }
adafruit-ampy = "^1.1.0"
paho-mqtt = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
