[tool.poetry]
name = "evoflow-reactor"
version = "0.1.0"
description = ""
authors = ["Sasha Melkonyan <sasha.melkonyan@gmail.com>"]
readme = "README.md"

packages = [
    { include = "diagnostics" },
    { include = "calibration" },
    { include = "setup-tool"}
]

[tool.poetry.dependencies]
python = "^3.12"
rshell = "^0.0.32"
evoflow_db = { git = "git@github.com:Schwank-Lab/evoflow-monitor.git", branch = "main", subdirectory = "evohub/evoflow_db" }
adafruit-ampy = "^1.1.0"
paho-mqtt = "^2.1.0"
jupyter = "^1.0.0"
pyserial = "^3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
